config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :packlists

  root 'packlists#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :packlist
end

app/models/packlist.rb
class Packlist < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  after_create :calculate_articles

  def calculate_articles
    packlist = { }
    basic_items = ["Wallet", "ID", "Cash", "House Keys", "Phone", "Phone Charger", "Toiletries"]
    basic_items.each do |item|
      packlist[item] = 1
    end

    clothing = ["Shirts", "Pants", "Shoes", "Pairs of Socks", "Underwear", "Pajamas"]
    clothing.each do |clothing|
      packlist[clothing] = 1 * self.how_long
    end

    cold_clothing = ["Jackets", "Coats", "Sweaters", "Thermals", "Boots", "Beanies"]
      if self.weather.split(",").include? "Freezing"
        cold_clothing.each do |cold|
        packlist[cold] = 1 * self.how_long
        end
      end

    cool_clothing = ["Jackets", "Sweaters", "Beanies"]
      if self.weather.split(",").include? "Cool"
        cool_clothing.each do |cool|
          packlist[cool] = 1 * self.how_long
        end
      end

    warm_clothing = ["T-shirts", "Shorts", "Tennis Shoes", "Ankle Socks", "Hats", "Sunglasses"]
      if self.weather.split(",").include? "Warm"
        warm_clothing.each do |warm|
        packlist[warm] = 1 * self.how_long
        end
      end

    hot_clothing = ["T-shirts", "Shorts", "Tank Tops", "Sandals"]
      if self.weather.split(",").include? "Blazing"
        hot_clothing.each do |hot|
        packlist[hot] = 1 * self.how_long
        end
      end

      outdoor = ["Sunscreen", "Sunglasses", "Hats"]
      indoor = ["Lounge Clothes"]
      if self.activities == "Outdoor Activities"
        outdoor.each do |outdoor|
          packlist[outdoor] = 1 * self.how_long
        end
      elsif self.activities == "Indoor Activities"
        indoor.each do |indoor|
          packlist[indoor] = 1 * self.how_long
        end
      end

    packlist.each do |key, value|
      self.items.create(article: key, quantity: value)
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/packlists_controller.rb
class PacklistsController < ApplicationController
  before_action :set_packlist, only: [:show, :edit, :update, :destroy]

  def new
    @packlist = Packlist.new
    @country_options = ["In Country", "Out of Country"]
    @temp = [["Freezing"], ["Cool"], ["Warm"], ["Blazing"]]
    @time_frame = (1..30).to_a
    @activity_list = ['Outdoor Activities', 'Indoor Activities']
  end

  # def index
  #   @packlists = Packlist.all
  # end

  def create
    params["packlist"]["weather"] = params["packlist"]["weather"].reject {|x| x.empty?}.join(",")
    @packlist = Packlist.new(packlist_params)
    if @packlist.save
      redirect_to packlist_path(@packlist)
    else
      render :new
    end
  end

  def edit
    @packlist = Packlist.find(params[:id])
  end

  def update
    if @packlist.update_attributes(update_packlist_params)
      redirect_to packlist_path(@packlist)
    else
      render :edit
    end
  end

  def destroy
    if @packlist.destroy
      redirect_to packlist_path
    else
      render :new
    end
  end

  def show
    @items = @packlist.items
  end

  # def send_list
  #   @packlist = Packlist.find(params[:packlist_id])
  #   PacklistMailer.list_email(params[:packlist][:email], @packlist.id).deliver
  #   redirect_to @packlist, notice: 'Email sent!'
  # end

  private

  def set_packlist
    @packlist = Packlist.find(params[:id])
  end

  def packlist_params
    params.require(:packlist).permit(:where, :how_long, :weather, :activities)
  end

  def update_packlist_params
    params.require(:packlist).permit(items_attributes: [:id, :article, :quantity, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packlists_helper.rb
module PacklistsHelper
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h2 class="my-brand">
        <%= image_tag "packing.jpg", class: "navbar logo" %>
        The Packer Tracker
      </h2>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse pull-right pad-top" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav navbar-right"> -->
        
        <%= link_to "New Packlist", root_path, class: 'btn btn-success pad-10' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Packerpro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/nav_bar' %>
  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
	</div>
</body>
</html>

app/views/packlists/_form.html.erb
<%= simple_form_for(@packlist, class: 'vertical_form') do |f| %>

	<%= f.input :where, as: :radio_buttons, collection: @country_options, label: 'Where are you traveling?'%>

	<%= f.input :how_long, prompt: 'Days', collection: @time_frame, label: 'How long is you trip?' %>

	<%= f.label 'What is the weather supposed to be like?' %>

	<%= f.collection_check_boxes :weather, @temp, :first, :last, label_html: { class: "not-inline" } %>

	<%= f.input :activities, prompt: 'Options', collection: @activity_list, label: 'What kind of activities will you be doing?' %>

	<%= f.button :submit, "Generate List", class: "my-button" %>
<% end %>

app/views/packlists/_item_fields.html.erb
<div class="nested-fields">
  <li class="list-group-item col-md-4">
    <%= f.input :article %>
    <%= f.input :quantity %>
    <%= link_to_remove_association "remove item", f, class: "btn btn-danger" %>
  </li>


</div>

app/views/packlists/create.html.erb
<h1>Packlists#create</h1>
<p>Find me in app/views/packlists/create.html.erb</p>

app/views/packlists/edit.html.erb
<%= simple_form_for(@packlist) do |f| %>

  <h3>Edit Items</h3>
  <div id="items">
    <ul class="list-group row text-capitalize">
    <%= f.simple_fields_for :items do |item| %>
      <% render 'item_fields', :f => item %>
    <% end %>
    </ul>
    <div class="links">
      <%= link_to_add_association "Add item", f, :items, class: "btn btn-info" %>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

<%= link_to 'Back', packlist_path(@packlist), class: "btn btn-default" %>

app/views/packlists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

app/views/packlists/show.html.erb
    <h1 class="container text-center"><u>Your Packing List</u></h1><br>

      <ul class="list-group row text-capitalize">
        <% @items.each do |item| %>
  	      <li class="list-group-item col-md-4">
    	      <%= item.article %>:
              <span class="badge">
    	          <%= item.quantity %>
              </span>
  	      </li>

	      <% end %>
      </ul>

  <%= link_to 'Edit List', edit_packlist_path(@packlist), class: "btn btn-warning" %>